-- MySQL Script generated by MySQL Workbench
-- Mon Feb 28 16:54:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SocialNetwork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SocialNetwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SocialNetwork` DEFAULT CHARACTER SET utf8 ;
USE `SocialNetwork` ;

-- -----------------------------------------------------
-- Table `SocialNetwork`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialNetwork`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `birthday` DATE NULL,
  `gender` TINYINT(1) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `profilpic` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `SocialNetwork`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialNetwork`.`posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NULL,
  `img` VARCHAR(45) NULL,
  `creationdate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`, `idUser`),
  INDEX `fk_posts_users_idx` (`idUser` ASC),
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`idUser`)
    REFERENCES `SocialNetwork`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialNetwork`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialNetwork`.`friends` (
  `id` INT(11) NOT NULL,
  `idMe` INT(11) NOT NULL,
  `idFriend` INT(11) NOT NULL,
  `accept` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `idMe`, `idFriend`),
  INDEX `fk_friends_users1_idx` (`idMe` ASC),
  INDEX `fk_friends_users2_idx` (`idFriend` ASC),
  CONSTRAINT `fk_friends_users1`
    FOREIGN KEY (`idMe`)
    REFERENCES `SocialNetwork`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friends_users2`
    FOREIGN KEY (`idFriend`)
    REFERENCES `SocialNetwork`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialNetwork`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialNetwork`.`likes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser` INT(11) NOT NULL,
  `idPost` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `idPost`, `idUser`),
  INDEX `fk_likes_users1_idx` (`idUser` ASC),
  INDEX `fk_likes_posts1_idx` (`idPost` ASC),
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `SocialNetwork`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_posts1`
    FOREIGN KEY (`idPost`)
    REFERENCES `SocialNetwork`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
