-- MySQL Script generated by MySQL Workbench
-- Tue Mar 15 19:53:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SocialNetwork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SocialNetwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SocialNetwork` DEFAULT CHARACTER SET utf8 ;
USE `SocialNetwork` ;

-- -----------------------------------------------------
-- Table `SocialNetwork`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SocialNetwork`.`users` ;

CREATE TABLE IF NOT EXISTS `SocialNetwork`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `birthday` DATE NULL,
  `gender` TINYINT(1) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `profilpic` VARCHAR(245) NOT NULL DEFAULT 'user',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `SocialNetwork`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SocialNetwork`.`posts` ;

CREATE TABLE IF NOT EXISTS `SocialNetwork`.`posts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NULL,
  `img` VARCHAR(45) NULL,
  `creationdate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`, `idUser`),
  INDEX `fk_posts_users_idx` (`idUser` ASC),
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`idUser`)
    REFERENCES `SocialNetwork`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialNetwork`.`friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SocialNetwork`.`friends` ;

CREATE TABLE IF NOT EXISTS `SocialNetwork`.`friends` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idMe` INT(11) NOT NULL,
  `idFriend` INT(11) NOT NULL,
  `accept` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `idMe`, `idFriend`),
  INDEX `fk_friends_users1_idx` (`idMe` ASC),
  INDEX `fk_friends_users2_idx` (`idFriend` ASC),
  CONSTRAINT `fk_friends_users1`
    FOREIGN KEY (`idMe`)
    REFERENCES `SocialNetwork`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friends_users2`
    FOREIGN KEY (`idFriend`)
    REFERENCES `SocialNetwork`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialNetwork`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SocialNetwork`.`likes` ;

CREATE TABLE IF NOT EXISTS `SocialNetwork`.`likes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser` INT(11) NOT NULL,
  `idPost` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `idPost`, `idUser`),
  INDEX `fk_likes_users1_idx` (`idUser` ASC),
  INDEX `fk_likes_posts1_idx` (`idPost` ASC),
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `SocialNetwork`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_posts1`
    FOREIGN KEY (`idPost`)
    REFERENCES `SocialNetwork`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SocialNetwork`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `SocialNetwork`;
INSERT INTO `SocialNetwork`.`users` (`id`, `username`, `name`, `birthday`, `gender`, `email`, `password`, `profilpic`, `create_time`, `status`) VALUES (1, 'jane.cooper', 'Jane Cooper', '1988-10-14', 0, 'jane.cooper@example.com', '12345', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60', '2011-03-13 02:53:50', 0);
INSERT INTO `SocialNetwork`.`users` (`id`, `username`, `name`, `birthday`, `gender`, `email`, `password`, `profilpic`, `create_time`, `status`) VALUES (2, 'euby.sanchez', 'Euby Sanchez', '1988-10-14', 1, 'euby.sanchez@example.com', '12345', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60', '2011-03-14 02:53:50', 0);
INSERT INTO `SocialNetwork`.`users` (`id`, `username`, `name`, `birthday`, `gender`, `email`, `password`, `profilpic`, `create_time`, `status`) VALUES (3, 'fernanda.denobrega', 'Fernanda De Nobrega', '1996-10-04', 0, 'fernanda.denobrega@example.com', '12345', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60', '2011-03-14 02:53:50', 0);
INSERT INTO `SocialNetwork`.`users` (`id`, `username`, `name`, `birthday`, `gender`, `email`, `password`, `profilpic`, `create_time`, `status`) VALUES (4, 'eukarys.millan', 'Eukarys Millan', '2006-10-10', 0, 'eukarys.millan@example.com', '12345', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60', '2011-03-14 02:53:50', 0);
INSERT INTO `SocialNetwork`.`users` (`id`, `username`, `name`, `birthday`, `gender`, `email`, `password`, `profilpic`, `create_time`, `status`) VALUES (DEFAULT, 'erik.sanchez', 'Erik Sanchez', '1990-10-12', 1, 'erik.sanchez@example.com', '12345', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60', '2011-03-14 02:53:50', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `SocialNetwork`.`posts`
-- -----------------------------------------------------
START TRANSACTION;
USE `SocialNetwork`;
INSERT INTO `SocialNetwork`.`posts` (`id`, `content`, `img`, `creationdate`, `idUser`) VALUES (DEFAULT, 'aprendiendo a programar', NULL, '2011-03-13 02:53:50', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `SocialNetwork`.`friends`
-- -----------------------------------------------------
START TRANSACTION;
USE `SocialNetwork`;
INSERT INTO `SocialNetwork`.`friends` (`id`, `idMe`, `idFriend`, `accept`) VALUES (1, 2, 1, 1);
INSERT INTO `SocialNetwork`.`friends` (`id`, `idMe`, `idFriend`, `accept`) VALUES (2, 2, 3, 1);
INSERT INTO `SocialNetwork`.`friends` (`id`, `idMe`, `idFriend`, `accept`) VALUES (3, 2, 4, 1);
INSERT INTO `SocialNetwork`.`friends` (`id`, `idMe`, `idFriend`, `accept`) VALUES (DEFAULT, 1, 2, 1);
INSERT INTO `SocialNetwork`.`friends` (`id`, `idMe`, `idFriend`, `accept`) VALUES (DEFAULT, 1, 3, 1);

COMMIT;

